### ISSUE TITLE
What's your program result?

### ISSUE THREAD

**Issue by blackcoding** [CulDeVu/ParticleNavier#1]
I download your program and run it. But I don't think that it was the right result. Can you give me the screenshot when you run your program. Thank you very much. Poorly English! Please forgive me.
You can email to m. 
Email address : 601900913@qq.com

**Comment by CulDeVu** [comment]
I modified some of the constants and debug logic to make it a bit easier to run it, if you want to try again. If you want to learn from this code, I suggest finding a cleaner repository, or reading the paper that this implementation came from. My code here is really messy and hard to understand.

Here are some screenshots: 
![screenshot 2016-11-12 09 23 24](https://cloud.githubusercontent.com/assets/2807131/20238575/adb2640c-a8bc-11e6-9da8-2b9d78a65199.png)
![screenshot 2016-11-12 09 36 57](https://cloud.githubusercontent.com/assets/2807131/20238577/adb366ae-a8bc-11e6-8a55-ec055ad2188c.png)
![screenshot 2016-11-12 09 37 06](https://cloud.githubusercontent.com/assets/2807131/20238576/adb33954-a8bc-11e6-9055-e1680cafa073.png)

**Comment by blackcoding** [comment]
Thank you very much!
